import csv
import requests


class playerFields:
    def __init__(self, rk, player, team, pos, g, ab, r, h, doubles, triples, homeRuns, rbis, so, sb, cs, avg, obp, slg, ops):
        self.rk = rk
        self.player = player
        self.team = team
        self.pos = pos
        self.g = g
        self.ab = ab
        self.r = r
        self.h = h
        self.double = doubles
        self.triples = triples
        self.homeRuns = homeRuns
        self.rbis = rbis
        self.so = so
        self.sb = sb
        self.cs = cs
        self.avg = avg
        self.obp = obp
        self.slg = slg
        self.ops = ops





baseball_data = 'http://mlb.mlb.com/pubajax/wf/flow/stats.splayer?season=2019&sort_order=%27desc%27&sort_column=%27hr%27&stat_type=hitting&page_type=SortablePlayer&game_type=%27R%27&player_pool=QUALIFIER&season_type=ANY&sport_code=%27mlb%27&results=1000&recSP=1&recPP=50'

response = requests.get(baseball_data)
response.raise_for_status()
p0 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][0]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][0]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][0]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][0]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][0]['g'], response.json()['stats_sortable_player']['queryResults']['row'][0]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][0]['r'], response.json()['stats_sortable_player']['queryResults']['row'][0]['h'], response.json()['stats_sortable_player']['queryResults']['row'][0]['d'], response.json()['stats_sortable_player']['queryResults']['row'][0]['t'], response.json()['stats_sortable_player']['queryResults']['row'][0]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][0]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][0]['so'], response.json()['stats_sortable_player']['queryResults']['row'][0]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][0]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][0]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][0]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][0]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][0]['ops'])
p1 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][1]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][1]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][1]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][1]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][1]['g'], response.json()['stats_sortable_player']['queryResults']['row'][1]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][1]['r'], response.json()['stats_sortable_player']['queryResults']['row'][1]['h'], response.json()['stats_sortable_player']['queryResults']['row'][1]['d'], response.json()['stats_sortable_player']['queryResults']['row'][1]['t'], response.json()['stats_sortable_player']['queryResults']['row'][1]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][1]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][1]['so'], response.json()['stats_sortable_player']['queryResults']['row'][1]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][1]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][1]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][1]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][1]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][1]['ops'])
p2 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][2]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][2]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][2]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][2]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][2]['g'], response.json()['stats_sortable_player']['queryResults']['row'][2]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][2]['r'], response.json()['stats_sortable_player']['queryResults']['row'][2]['h'], response.json()['stats_sortable_player']['queryResults']['row'][2]['d'], response.json()['stats_sortable_player']['queryResults']['row'][2]['t'], response.json()['stats_sortable_player']['queryResults']['row'][2]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][2]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][2]['so'], response.json()['stats_sortable_player']['queryResults']['row'][2]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][2]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][2]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][2]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][2]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][2]['ops'])
p3 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][3]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][3]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][3]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][3]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][3]['g'], response.json()['stats_sortable_player']['queryResults']['row'][3]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][3]['r'], response.json()['stats_sortable_player']['queryResults']['row'][3]['h'], response.json()['stats_sortable_player']['queryResults']['row'][3]['d'], response.json()['stats_sortable_player']['queryResults']['row'][3]['t'], response.json()['stats_sortable_player']['queryResults']['row'][3]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][3]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][3]['so'], response.json()['stats_sortable_player']['queryResults']['row'][3]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][3]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][3]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][3]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][3]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][3]['ops'])
p4 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][4]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][4]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][4]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][4]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][4]['g'], response.json()['stats_sortable_player']['queryResults']['row'][4]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][4]['r'], response.json()['stats_sortable_player']['queryResults']['row'][4]['h'], response.json()['stats_sortable_player']['queryResults']['row'][4]['d'], response.json()['stats_sortable_player']['queryResults']['row'][4]['t'], response.json()['stats_sortable_player']['queryResults']['row'][4]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][4]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][4]['so'], response.json()['stats_sortable_player']['queryResults']['row'][4]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][4]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][4]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][4]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][4]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][4]['ops'])
p5 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][5]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][5]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][5]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][5]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][5]['g'], response.json()['stats_sortable_player']['queryResults']['row'][5]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][5]['r'], response.json()['stats_sortable_player']['queryResults']['row'][5]['h'], response.json()['stats_sortable_player']['queryResults']['row'][5]['d'], response.json()['stats_sortable_player']['queryResults']['row'][5]['t'], response.json()['stats_sortable_player']['queryResults']['row'][5]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][5]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][5]['so'], response.json()['stats_sortable_player']['queryResults']['row'][5]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][5]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][5]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][5]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][5]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][5]['ops'])
p6 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][6]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][6]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][6]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][6]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][6]['g'], response.json()['stats_sortable_player']['queryResults']['row'][6]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][6]['r'], response.json()['stats_sortable_player']['queryResults']['row'][6]['h'], response.json()['stats_sortable_player']['queryResults']['row'][6]['d'], response.json()['stats_sortable_player']['queryResults']['row'][6]['t'], response.json()['stats_sortable_player']['queryResults']['row'][6]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][6]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][6]['so'], response.json()['stats_sortable_player']['queryResults']['row'][6]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][6]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][6]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][6]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][6]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][6]['ops'])
p7 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][7]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][7]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][7]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][7]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][7]['g'], response.json()['stats_sortable_player']['queryResults']['row'][7]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][7]['r'], response.json()['stats_sortable_player']['queryResults']['row'][7]['h'], response.json()['stats_sortable_player']['queryResults']['row'][7]['d'], response.json()['stats_sortable_player']['queryResults']['row'][7]['t'], response.json()['stats_sortable_player']['queryResults']['row'][7]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][7]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][7]['so'], response.json()['stats_sortable_player']['queryResults']['row'][7]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][7]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][7]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][7]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][7]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][7]['ops'])
p8 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][8]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][8]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][8]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][8]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][8]['g'], response.json()['stats_sortable_player']['queryResults']['row'][8]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][8]['r'], response.json()['stats_sortable_player']['queryResults']['row'][8]['h'], response.json()['stats_sortable_player']['queryResults']['row'][8]['d'], response.json()['stats_sortable_player']['queryResults']['row'][8]['t'], response.json()['stats_sortable_player']['queryResults']['row'][8]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][8]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][8]['so'], response.json()['stats_sortable_player']['queryResults']['row'][8]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][8]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][8]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][8]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][8]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][8]['ops'])
p9 = playerFields(response.json()['stats_sortable_player']['queryResults']['row'][9]['rank'], response.json()['stats_sortable_player']['queryResults']['row'][9]['name_display_first_last'], response.json()['stats_sortable_player']['queryResults']['row'][9]['team_abbrev'], response.json()['stats_sortable_player']['queryResults']['row'][9]['pos'], response.json()['stats_sortable_player']['queryResults']['row'][9]['g'], response.json()['stats_sortable_player']['queryResults']['row'][9]['ab'], response.json()['stats_sortable_player']['queryResults']['row'][9]['r'], response.json()['stats_sortable_player']['queryResults']['row'][9]['h'], response.json()['stats_sortable_player']['queryResults']['row'][9]['d'], response.json()['stats_sortable_player']['queryResults']['row'][9]['t'], response.json()['stats_sortable_player']['queryResults']['row'][9]['hr'], response.json()['stats_sortable_player']['queryResults']['row'][9]['rbi'], response.json()['stats_sortable_player']['queryResults']['row'][9]['so'], response.json()['stats_sortable_player']['queryResults']['row'][9]['sb'], response.json()['stats_sortable_player']['queryResults']['row'][9]['cs'], response.json()['stats_sortable_player']['queryResults']['row'][9]['avg'], response.json()['stats_sortable_player']['queryResults']['row'][9]['obp'], response.json()['stats_sortable_player']['queryResults']['row'][9]['slg'], response.json()['stats_sortable_player']['queryResults']['row'][9]['ops'])


data = [['Rank', 'Player', 'Team', 'Pos', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SO', 'SB', 'CS', 'AVG', 'OBP', 'SLG', 'OPS'],
        [p0.rk, p0.player, p0.team, p0.pos, p0.g, p0.ab, p0.r, p0.h, p0.double, p0.triples, p0.homeRuns, p0.rbis, p0.so,
         p0.sb, p0.cs, p0.avg, p0.obp, p0.slg, p0.ops],
        [p1.rk, p1.player, p1.team, p1.pos, p1.g, p1.ab, p1.r, p1.h, p1.double, p1.triples, p1.homeRuns, p1.rbis, p1.so,
         p1.sb, p1.cs, p1.avg, p1.obp, p1.slg, p1.ops],
        [p2.rk, p2.player, p2.team, p2.pos, p2.g, p2.ab, p2.r, p2.h, p2.double, p2.triples, p2.homeRuns, p2.rbis, p2.so,
         p2.sb, p2.cs, p2.avg, p2.obp, p2.slg, p2.ops],
        [p3.rk, p3.player, p3.team, p3.pos, p3.g, p3.ab, p3.r, p3.h, p3.double, p3.triples, p3.homeRuns, p3.rbis, p3.so,
         p3.sb, p3.cs, p3.avg, p3.obp, p3.slg, p3.ops],
        [p4.rk, p4.player, p4.team, p4.pos, p4.g, p4.ab, p4.r, p4.h, p4.double, p4.triples, p4.homeRuns, p4.rbis, p4.so,
         p4.sb, p4.cs, p4.avg, p4.obp, p4.slg, p4.ops],
        [p5.rk, p5.player, p5.team, p5.pos, p5.g, p5.ab, p5.r, p5.h, p5.double, p5.triples, p5.homeRuns, p5.rbis, p5.so,
         p5.sb, p5.cs, p5.avg, p5.obp, p5.slg, p5.ops],
        [p6.rk, p6.player, p6.team, p6.pos, p6.g, p6.ab, p6.r, p6.h, p6.double, p6.triples, p6.homeRuns, p6.rbis, p6.so,
         p6.sb, p6.cs, p6.avg, p6.obp, p6.slg, p6.ops],
        [p7.rk, p7.player, p7.team, p7.pos, p7.g, p7.ab, p7.r, p7.h, p7.double, p7.triples, p7.homeRuns, p7.rbis, p7.so,
         p7.sb, p7.cs, p7.avg, p7.obp, p7.slg, p7.ops],
        [p8.rk, p8.player, p8.team, p8.pos, p8.g, p8.ab, p8.r, p8.h, p8.double, p8.triples, p8.homeRuns, p8.rbis, p8.so,
         p8.sb, p8.cs, p8.avg, p8.obp, p8.slg, p8.ops],
        [p9.rk, p9.player, p9.team, p9.pos, p9.g, p9.ab, p9.r, p9.h, p9.double, p9.triples, p9.homeRuns, p9.rbis, p9.so,
         p9.sb, p9.cs, p9.avg, p9.obp, p9.slg, p9.ops]]

rank1AVG = response.json()['stats_sortable_player']['queryResults']['row'][0]['avg']
with open('hr.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data)


csvFile.close()


# https://www.youtube.com/watch?v=jVZkQL446Ks